export interface MockBroker {
  _id: string;
  name: string;
  slug: string;
  logo: string;
  country: string;
  headquarters?: string;
  regulation: string[];
  regulators?: string[];
  rating: number;
  totalReviews: number;
  safetyScore: number;
  minDeposit: number;
  maxLeverage: string;
  leverage?: string;
  eurUsdSpread: number;
  spreadType: string;
  tradingPlatforms: string[];
  platforms?: string[];
  accountTypes?: Array<{ name: string; minDeposit: number; leverage: string; spread: string; commission: string }>;
  paymentMethods: string[];
  website: string;
  description: string;
  featured?: boolean;
  isFeatured?: boolean;
  approvalStatus: string;
  scamWarning?: boolean;
  scamDetails?: string;
  [key: string]: any;
}

export const MOCK_BROKERS: MockBroker[] = [
  {
    _id: 'b1',
    name: 'Pepperstone',
    slug: 'pepperstone',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=120&auto=format&fit=crop&q=80',
    country: 'Australia',
    headquarters: 'Melbourne, Australia',
    regulation: ['ASIC', 'FCA', 'CySEC', 'DFSA'],
    regulators: ['ASIC', 'FCA', 'CySEC', 'DFSA'],
    rating: 4.9,
    totalReviews: 480,
    safetyScore: 98,
    minDeposit: 0,
    maxLeverage: '1:500',
    leverage: '1:500',
    eurUsdSpread: 0.1,
    spreadType: 'Raw / ECN',
    tradingPlatforms: ['MetaTrader 4', 'MetaTrader 5', 'cTrader', 'TradingView'],
    platforms: ['MetaTrader 4', 'MetaTrader 5', 'cTrader', 'TradingView'],
    accountTypes: [
      { name: 'Razor (ECN)', minDeposit: 0, leverage: '1:500', spread: '0.0 pips', commission: '$3.50/side' },
      { name: 'Standard', minDeposit: 0, leverage: '1:500', spread: '0.8 pips', commission: 'Zero' },
    ],
    paymentMethods: ['Bank Wire', 'Credit Card', 'PayPal', 'Neteller', 'Crypto'],
    website: 'https://pepperstone.com',
    description: 'Tier-1 regulated multi-asset broker providing razor-thin spreads, institutional liquidity access, and ultra-fast execution across global markets.',
    featured: true,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'b2',
    name: 'IC Markets',
    slug: 'ic-markets',
    logo: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=120&auto=format&fit=crop&q=80',
    country: 'Australia',
    headquarters: 'Sydney, Australia',
    regulation: ['ASIC', 'CySEC', 'FSA'],
    regulators: ['ASIC', 'CySEC', 'FSA'],
    rating: 4.8,
    totalReviews: 395,
    safetyScore: 95,
    minDeposit: 200,
    maxLeverage: '1:500',
    leverage: '1:500',
    eurUsdSpread: 0.0,
    spreadType: 'Raw / ECN',
    tradingPlatforms: ['MetaTrader 4', 'MetaTrader 5', 'cTrader'],
    platforms: ['MetaTrader 4', 'MetaTrader 5', 'cTrader'],
    accountTypes: [
      { name: 'Raw Spread', minDeposit: 200, leverage: '1:500', spread: '0.0 pips', commission: '$3.50/side' },
      { name: 'Standard', minDeposit: 200, leverage: '1:500', spread: '0.8 pips', commission: 'Zero' },
    ],
    paymentMethods: ['Bank Wire', 'Credit Card', 'PayPal', 'Skrill', 'Crypto'],
    website: 'https://icmarkets.com',
    description: 'Renowned true ECN broker connected to Equinix NY4 servers in New York, ideal for automated algorithmic EAs and high-volume day traders.',
    featured: true,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'b3',
    name: 'XM Global',
    slug: 'xm-global',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
    country: 'Cyprus',
    headquarters: 'Limassol, Cyprus',
    regulation: ['CySEC', 'FCA', 'ASIC', 'FSC'],
    regulators: ['CySEC', 'FCA', 'ASIC', 'FSC'],
    rating: 4.7,
    totalReviews: 310,
    safetyScore: 92,
    minDeposit: 5,
    maxLeverage: '1:1000',
    leverage: '1:1000',
    eurUsdSpread: 0.6,
    spreadType: 'Standard / Variable',
    tradingPlatforms: ['MetaTrader 4', 'MetaTrader 5'],
    platforms: ['MetaTrader 4', 'MetaTrader 5'],
    accountTypes: [
      { name: 'Micro', minDeposit: 5, leverage: '1:1000', spread: '1.0 pips', commission: 'Zero' },
      { name: 'Ultra Low', minDeposit: 50, leverage: '1:1000', spread: '0.6 pips', commission: 'Zero' },
    ],
    paymentMethods: ['Credit Card', 'Bank Wire', 'Neteller', 'Skrill', 'Crypto'],
    website: 'https://xm.com',
    description: 'Global brokerage trusted by over 10 million clients featuring zero requotes, negative balance protection, and low minimum deposit.',
    featured: true,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'b4',
    name: 'Exness',
    slug: 'exness',
    logo: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=120&auto=format&fit=crop&q=80',
    country: 'Cyprus',
    headquarters: 'Limassol, Cyprus',
    regulation: ['FCA', 'CySEC', 'FSCA', 'FSA'],
    regulators: ['FCA', 'CySEC', 'FSCA', 'FSA'],
    rating: 4.8,
    totalReviews: 520,
    safetyScore: 94,
    minDeposit: 10,
    maxLeverage: '1:2000',
    leverage: '1:2000',
    eurUsdSpread: 0.2,
    spreadType: 'Raw / ECN',
    tradingPlatforms: ['MetaTrader 4', 'MetaTrader 5', 'TradingView'],
    platforms: ['MetaTrader 4', 'MetaTrader 5', 'TradingView'],
    accountTypes: [
      { name: 'Standard', minDeposit: 10, leverage: '1:2000', spread: '0.3 pips', commission: 'Zero' },
      { name: 'Raw Spread', minDeposit: 200, leverage: '1:2000', spread: '0.0 pips', commission: '$3.50/side' },
    ],
    paymentMethods: ['Crypto', 'Credit Card', 'Bank Wire', 'Skrill', 'Neteller'],
    website: 'https://exness.com',
    description: 'Market leader in trading volume with instant automated withdrawals, tightest stable spreads during high volatility, and flexible leverage.',
    featured: true,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'b5',
    name: 'Vantage Prime Markets',
    slug: 'vantage-prime',
    logo: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=120&auto=format&fit=crop&q=80',
    country: 'Australia',
    headquarters: 'Sydney, Australia',
    regulation: ['ASIC', 'CIMA', 'VFSC'],
    regulators: ['ASIC', 'CIMA', 'VFSC'],
    rating: 4.6,
    totalReviews: 240,
    safetyScore: 90,
    minDeposit: 100,
    maxLeverage: '1:1000',
    leverage: '1:1000',
    eurUsdSpread: 0.2,
    spreadType: 'Raw / ECN',
    tradingPlatforms: ['MetaTrader 4', 'MetaTrader 5', 'TradingView'],
    platforms: ['MetaTrader 4', 'MetaTrader 5', 'TradingView'],
    accountTypes: [
      { name: 'Raw ECN', minDeposit: 100, leverage: '1:1000', spread: '0.0 pips', commission: '$3.00/side' },
    ],
    paymentMethods: ['Credit Card', 'Bank Wire', 'Crypto'],
    website: 'https://vantagemarkets.com',
    description: 'Fast-growing multi-asset broker with premium TradingView integration, deep liquidity pools, and client segregated accounts.',
    featured: false,
    isFeatured: false,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'b6',
    name: 'FXTM (ForexTime)',
    slug: 'fxtm',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    headquarters: 'London, United Kingdom',
    regulation: ['FCA', 'CySEC', 'FSCA'],
    regulators: ['FCA', 'CySEC', 'FSCA'],
    rating: 4.5,
    totalReviews: 180,
    safetyScore: 89,
    minDeposit: 50,
    maxLeverage: '1:500',
    leverage: '1:500',
    eurUsdSpread: 0.4,
    spreadType: 'Standard / Variable',
    tradingPlatforms: ['MetaTrader 4', 'MetaTrader 5'],
    platforms: ['MetaTrader 4', 'MetaTrader 5'],
    accountTypes: [
      { name: 'Advantage', minDeposit: 500, leverage: '1:500', spread: '0.0 pips', commission: '$2.00/side' },
      { name: 'Micro', minDeposit: 50, leverage: '1:500', spread: '1.2 pips', commission: 'Zero' },
    ],
    paymentMethods: ['Bank Wire', 'Credit Card', 'Skrill', 'Crypto'],
    website: 'https://fxtm.com',
    description: 'Regulated UK broker providing comprehensive trading education, swap-free trading conditions, and fast execution.',
    featured: false,
    isFeatured: false,
    approvalStatus: 'approved',
    status: 'active',
  },
];

export const MOCK_ACCOUNT_MANAGERS: any[] = [
  {
    _id: 'am1',
    name: 'Marcus Vance',
    company: 'Aurelius Capital PAMM',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=256&auto=format&fit=crop&q=80',
    experience: '9+ years',
    strategy: 'Institutional SMC Liquidity & Order Flow',
    minInvestment: 1000,
    historicalPerformance: {
      monthlyReturn: 14.8,
      maxDrawdown: 6.2,
      winRate: 78.5,
      totalPips: 8400,
      trackRecordUrl: 'https://myfxbook.com',
    },
    riskInfo: 'Maximum 1.5% capital risk per trade. Zero Martingale, mandatory stop losses on all orders.',
    tradingStyle: 'Day Trading',
    description: 'Institutional macro order flow manager focusing on London and New York overlaps across major pairs.',
    contactEmail: 'marcus@aurelius.example.com',
    rating: 4.9,
    totalReviews: 84,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'am2',
    name: 'Elena Rostova',
    company: 'QuantEdge Alpha Fund',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=256&auto=format&fit=crop&q=80',
    experience: '7+ years',
    strategy: 'Algorithmic Mean-Reversion & Statistical Arbitrage',
    minInvestment: 2500,
    historicalPerformance: {
      monthlyReturn: 11.2,
      maxDrawdown: 4.5,
      winRate: 82.0,
      totalPips: 12500,
      trackRecordUrl: 'https://myfxbook.com',
    },
    riskInfo: 'Dynamic portfolio volatility parity model with automatic circuit-breaker cutoff at 5% drawdown.',
    tradingStyle: 'Algorithmic/EA',
    description: 'Former quantitative analyst operating low-latency statistical arbitrage EAs on ECN cross-connects.',
    contactEmail: 'elena@quantedge.example.com',
    rating: 4.8,
    totalReviews: 62,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
  {
    _id: 'am3',
    name: 'Jonathan Sterling',
    company: 'Highfield Global Wealth',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=256&auto=format&fit=crop&q=80',
    experience: '12+ years',
    strategy: 'Multi-Week Macro Swing & FX Carry Trade',
    minInvestment: 5000,
    historicalPerformance: {
      monthlyReturn: 9.6,
      maxDrawdown: 7.1,
      winRate: 74.0,
      totalPips: 9800,
      trackRecordUrl: 'https://myfxbook.com',
    },
    riskInfo: 'Conservative swing positions aligned with central bank rate differentials and structural trend models.',
    tradingStyle: 'Swing',
    description: 'Long-term FX portfolio manager delivering steady non-correlated alpha for high net worth clients.',
    contactEmail: 'j.sterling@highfield.example.com',
    rating: 4.7,
    totalReviews: 45,
    isFeatured: true,
    approvalStatus: 'approved',
    status: 'active',
  },
];

export const MOCK_MANAGERS = MOCK_ACCOUNT_MANAGERS;

export const MOCK_SIGNAL_PROVIDERS: any[] = [
  {
    _id: 'sp1',
    name: 'Apex Quantitative Feeds',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&auto=format&fit=crop&q=80',
    strategy: 'Institutional Price Action & Market Structure Breakouts',
    markets: ['EUR/USD', 'GBP/USD', 'XAU/USD', 'USD/JPY'],
    subscriptionPrice: 49,
    historicalPerformance: {
      winRate: 82.5,
      monthlyRoi: 18.2,
      maxDrawdown: 5.8,
      totalSignals: 420,
      avgPipsPerMonth: 950,
    },
    riskInfo: 'Strict 1:2.5 minimum Risk-to-Reward ratio with mandatory 25-pip stop loss and dual take-profit targets.',
    description: 'Systematic algorithmic signals derived from London/New York session overlaps with zero Martingale and zero Grid.',
    website: 'https://apexsignals.example.com',
    contactEmail: 'provider@apexsignals.com',
    rating: 4.9,
    totalReviews: 126,
    subscribersCount: 384,
    approvalStatus: 'approved',
    status: 'active',
    isFeatured: true,
  },
  {
    _id: 'sp2',
    name: 'London Breakout Sniper',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=256&auto=format&fit=crop&q=80',
    strategy: 'Frankfurt & London Opening Range Expansion',
    markets: ['GBP/JPY', 'EUR/JPY', 'GBP/USD'],
    subscriptionPrice: 79,
    historicalPerformance: {
      winRate: 76.0,
      monthlyRoi: 14.5,
      maxDrawdown: 7.2,
      totalSignals: 180,
      avgPipsPerMonth: 720,
    },
    riskInfo: 'Tight 15-pip stop loss on all European cross scalps. Capital preservation first.',
    description: 'High-momentum breakout strategy capturing morning European directional liquidity expansion.',
    website: 'https://londonbreakout.example.com',
    contactEmail: 'sniper@londonbreakout.example.com',
    rating: 4.7,
    totalReviews: 88,
    subscribersCount: 215,
    approvalStatus: 'approved',
    status: 'active',
    isFeatured: true,
  },
  {
    _id: 'sp3',
    name: 'PipMaster Pro Swings',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=256&auto=format&fit=crop&q=80',
    strategy: 'Multi-Timeframe Trend Continuation & Fibonacci Confluence',
    markets: ['EUR/USD', 'AUD/USD', 'USD/CAD', 'XAU/USD'],
    subscriptionPrice: 59,
    historicalPerformance: {
      winRate: 79.0,
      monthlyRoi: 16.0,
      maxDrawdown: 6.4,
      totalSignals: 310,
      avgPipsPerMonth: 880,
    },
    riskInfo: '1:3 Risk/Reward setups on H4 and Daily charts with trailing stop loss protection.',
    description: 'Patience-driven swing signal stream designed for working traders who cannot stare at screens all day.',
    website: 'https://pipmaster.example.com',
    contactEmail: 'support@pipmaster.example.com',
    rating: 4.8,
    totalReviews: 95,
    subscribersCount: 290,
    approvalStatus: 'approved',
    status: 'active',
    isFeatured: true,
  },
];

export const MOCK_COURSES: any[] = [
  {
    _id: 'c1',
    title: 'Institutional Smart Money Concepts (SMC) Masterclass',
    slug: 'institutional-smart-money-concepts-smc-masterclass',
    level: 'Advanced',
    category: 'Price Action',
    description: 'A comprehensive curriculum teaching retail traders how banks and institutional liquidity providers engineer price delivery in the global Forex market.',
    shortSummary: 'Master order blocks, fair value gaps, liquidity sweeps, and high-probability trade framing.',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    durationHours: 12.5,
    totalLessons: 18,
    studentsEnrolled: 1420,
    rating: 4.9,
    price: 199,
    instructor: {
      name: 'David Sutherland',
      role: 'Chief Technical Strategist',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    },
    tutor: {
      name: 'David Sutherland',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    },
    approvalStatus: 'approved',
    status: 'published',
  },
  {
    _id: 'c2',
    title: 'Forex Foundations & Technical Analysis for Beginners',
    slug: 'forex-foundations-technical-analysis-for-beginners',
    level: 'Beginner',
    category: 'Forex Basics',
    description: 'Step-by-step beginner guide to understanding currency quotes, leverage, order types, support/resistance, and candlestick charting patterns.',
    shortSummary: 'Everything you need to go from zero experience to executing disciplined, structured trades.',
    thumbnail: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=800&q=80',
    durationHours: 6.0,
    totalLessons: 12,
    studentsEnrolled: 2850,
    rating: 4.8,
    price: 49,
    instructor: {
      name: 'Sarah Jenkins',
      role: 'Senior FX Instructor',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    },
    tutor: {
      name: 'Sarah Jenkins',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    },
    approvalStatus: 'approved',
    status: 'published',
  },
  {
    _id: 'c3',
    title: 'Professional Risk Management & Position Sizing Framework',
    slug: 'professional-risk-management-position-sizing-framework',
    level: 'Intermediate',
    category: 'Risk Management',
    description: 'Learn institutional risk metrics: Value-at-Risk (VaR), dynamic Kelly criterion fraction sizing, Monte Carlo simulations, and drawdown recovery models.',
    shortSummary: 'Protect your trading capital with rigorous mathematical frameworks used by top hedge funds.',
    thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
    durationHours: 5.5,
    totalLessons: 8,
    studentsEnrolled: 980,
    rating: 4.95,
    price: 89,
    instructor: {
      name: 'Dr. Arthur Pendelton',
      role: 'Risk Governance Advisor',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    },
    tutor: {
      name: 'Dr. Arthur Pendelton',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    },
    approvalStatus: 'approved',
    status: 'published',
  },
  {
    _id: 'c4',
    title: 'Algorithmic Trading & EA Development in MQL5',
    slug: 'algorithmic-trading-ea-development-mql5',
    level: 'Advanced',
    category: 'EA & Algorithms',
    description: 'Build, backtest, stress-test, and deploy robust automated Expert Advisors in MetaTrader 5 with zero coding background required to start.',
    shortSummary: 'Automate your trading strategy and backtest across 10 years of tick data.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    durationHours: 14.0,
    totalLessons: 20,
    studentsEnrolled: 740,
    rating: 4.75,
    price: 149,
    instructor: {
      name: 'Viktor Chernov',
      role: 'Quantitative Developer',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    },
    tutor: {
      name: 'Viktor Chernov',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    },
    approvalStatus: 'approved',
    status: 'published',
  },
];

export const MOCK_COMPLAINTS: any[] = [
  {
    _id: 'cmp1',
    caseId: 'ETF-2026-8912',
    entityName: 'Unregulated Offshore Entity',
    category: 'Withdrawal Denial',
    amount: 14500,
    status: 'investigating',
    createdAt: '2026-03-12T10:00:00Z',
    description: 'Broker refused withdrawal request citing unauthorized bonus terms after profitable trading week.',
  },
  {
    _id: 'cmp2',
    caseId: 'ETF-2026-7821',
    entityName: 'Apex FX Markets',
    category: 'Artificial Slippage',
    amount: 6200,
    status: 'resolved',
    createdAt: '2026-02-28T14:30:00Z',
    description: 'Severe 45-pip slippage executed outside normal market spreads during calm Asian session.',
  },
];
