// AUTO-GENERATED from Dropbox_of__broker_.pdf. Do not hand-edit counts.
// Counts: REGULATOR 58 (+OTHER), LANGUAGE 133, CURRENCY 9 (+OTHER), LICENSE_STATUS 8, DEPOSIT_BONUS 21, LEVERAGE 23, TIMEFRAME 9
export type BrokerOptionSeed = { group: 'REGULATOR'|'LANGUAGE'|'CURRENCY'|'LICENSE_STATUS'|'DEPOSIT_BONUS'|'LEVERAGE'|'TIMEFRAME'; code: string; label: string; sortOrder: number; meta: Record<string, unknown> };
export const BROKER_OPTIONS: BrokerOptionSeed[] = [
  { group: "REGULATOR", code: "ASIC", label: "(ASIC) Australia Securities & Investment Commission", sortOrder: 1, meta: {"acronym": "ASIC", "kind": "REGULATOR", "pdfPosition": 1} },
  { group: "REGULATOR", code: "NFA", label: "(NFA) National Futures Association", sortOrder: 2, meta: {"acronym": "NFA", "kind": "REGULATOR", "pdfPosition": 2} },
  { group: "REGULATOR", code: "FMA", label: "(FMA) Financial Markets Authority", sortOrder: 3, meta: {"acronym": "FMA", "kind": "REGULATOR", "pdfPosition": 3} },
  { group: "REGULATOR", code: "SFC", label: "(SFC) Securities and Futures Commission of Hong Kong", sortOrder: 4, meta: {"acronym": "SFC", "kind": "REGULATOR", "pdfPosition": 4} },
  { group: "REGULATOR", code: "CGSE", label: "(CGSE) The Chinese Gold & Silver Exchange Society", sortOrder: 5, meta: {"acronym": "CGSE", "kind": "EXCHANGE", "pdfPosition": 5} },
  { group: "REGULATOR", code: "FSPR", label: "(FSPR) Financial Service Providers Register", sortOrder: 6, meta: {"acronym": "FSPR", "kind": "REGISTER", "pdfPosition": 6} },
  { group: "REGULATOR", code: "CFFEX", label: "(CFFEX) China Financial Futures Exchange", sortOrder: 7, meta: {"acronym": "CFFEX", "kind": "EXCHANGE", "pdfPosition": 7} },
  { group: "REGULATOR", code: "VFSC", label: "(VFSC) Vanuatu Financial Services Commission", sortOrder: 8, meta: {"acronym": "VFSC", "kind": "REGULATOR", "pdfPosition": 8} },
  { group: "REGULATOR", code: "FSC_09", label: "(FSC) British Virgin Islands Financial Services Commission", sortOrder: 9, meta: {"acronym": "FSC", "kind": "REGULATOR", "pdfPosition": 9} },
  { group: "REGULATOR", code: "FINMA", label: "(FINMA) Swiss Financial Market Supervisory Authority", sortOrder: 10, meta: {"acronym": "FINMA", "kind": "REGULATOR", "pdfPosition": 10} },
  { group: "REGULATOR", code: "FSA_11", label: "(FSA) The Seychelles Financial Services Authority", sortOrder: 11, meta: {"acronym": "FSA", "kind": "REGULATOR", "pdfPosition": 11} },
  { group: "REGULATOR", code: "CIMA", label: "(CIMA) Cayman Islands Monetary Authority", sortOrder: 12, meta: {"acronym": "CIMA", "kind": "REGULATOR", "pdfPosition": 12} },
  { group: "REGULATOR", code: "MFSA", label: "(MFSA) Malta Financial Services Authority", sortOrder: 13, meta: {"acronym": "MFSA", "kind": "REGULATOR", "pdfPosition": 13} },
  { group: "REGULATOR", code: "DFSA", label: "(DFSA) Dubai Financial Services Authority", sortOrder: 14, meta: {"acronym": "DFSA", "kind": "REGULATOR", "pdfPosition": 14} },
  { group: "REGULATOR", code: "SCB", label: "(SCB) The Securities Commission of The Bahamas", sortOrder: 15, meta: {"acronym": "SCB", "kind": "REGULATOR", "pdfPosition": 15} },
  { group: "REGULATOR", code: "BAFIN", label: "(BaFin) Federal Financial Supervisory Authority", sortOrder: 16, meta: {"acronym": "BaFin", "kind": "REGULATOR", "pdfPosition": 16} },
  { group: "REGULATOR", code: "FSA_17", label: "(FSA) Financial Services Agency", sortOrder: 17, meta: {"acronym": "FSA", "kind": "REGULATOR", "pdfPosition": 17} },
  { group: "REGULATOR", code: "AMF", label: "(AMF) The Autorité des Marchés Financiers", sortOrder: 18, meta: {"acronym": "AMF", "kind": "REGULATOR", "pdfPosition": 18} },
  { group: "REGULATOR", code: "CBR", label: "(CBR) Central Bank of Russia", sortOrder: 19, meta: {"acronym": "CBR", "kind": "REGULATOR", "pdfPosition": 19} },
  { group: "REGULATOR", code: "NBRB", label: "(NBRB) National Bank of the Republic of Belarus", sortOrder: 20, meta: {"acronym": "NBRB", "kind": "REGULATOR", "pdfPosition": 20} },
  { group: "REGULATOR", code: "FSCA", label: "(FSCA) Financial Sector Conduct Authority", sortOrder: 21, meta: {"acronym": "FSCA", "kind": "REGULATOR", "pdfPosition": 21} },
  { group: "REGULATOR", code: "CBI", label: "(CBI) Central Bank of Ireland", sortOrder: 22, meta: {"acronym": "CBI", "kind": "REGULATOR", "pdfPosition": 22} },
  { group: "REGULATOR", code: "FSC_23", label: "(FSC) The Financial Services Commission", sortOrder: 23, meta: {"acronym": "FSC", "kind": "REGULATOR", "pdfPosition": 23} },
  { group: "REGULATOR", code: "MAS", label: "(MAS) Monetary Authority of Singapore", sortOrder: 24, meta: {"acronym": "MAS", "kind": "REGULATOR", "pdfPosition": 24} },
  { group: "REGULATOR", code: "CNMV", label: "(CNMV) Comisión Nacional del Mercado de valores", sortOrder: 25, meta: {"acronym": "CNMV", "kind": "REGULATOR", "pdfPosition": 25} },
  { group: "REGULATOR", code: "SERC", label: "(SERC) Securities and Exchange Regulator of Cambodia", sortOrder: 26, meta: {"acronym": "SERC", "kind": "REGULATOR", "pdfPosition": 26} },
  { group: "REGULATOR", code: "BAPPEBTI", label: "(BAPPEBTI) Badan Pengawas Perdagangan Berjangka Komoditi Kementerian Perdagangan", sortOrder: 27, meta: {"acronym": "BAPPEBTI", "kind": "REGULATOR", "pdfPosition": 27} },
  { group: "REGULATOR", code: "CYSEC", label: "(CYSEC) Cyprus Securities and Exchange Commission", sortOrder: 28, meta: {"acronym": "CYSEC", "kind": "REGULATOR", "pdfPosition": 28} },
  { group: "REGULATOR", code: "FSC_29", label: "(FSC) Financial Services Commission", sortOrder: 29, meta: {"acronym": "FSC", "kind": "REGULATOR", "pdfPosition": 29} },
  { group: "REGULATOR", code: "FCA", label: "(FCA) Financial Conduct Authority", sortOrder: 30, meta: {"acronym": "FCA", "kind": "REGULATOR", "pdfPosition": 30} },
  { group: "REGULATOR", code: "SCM", label: "(SCM) The Securities Commission Malaysia", sortOrder: 31, meta: {"acronym": "SCM", "kind": "REGULATOR", "pdfPosition": 31} },
  { group: "REGULATOR", code: "AFSA", label: "(AFSA) The Astana Financial Services Authority", sortOrder: 32, meta: {"acronym": "AFSA", "kind": "REGULATOR", "pdfPosition": 32} },
  { group: "REGULATOR", code: "ISA", label: "(ISA) The Israel Securities Authority", sortOrder: 33, meta: {"acronym": "ISA", "kind": "REGULATOR", "pdfPosition": 33, "pdfNote": "pdf had trailing 'ISA' (artifact)"} },
  { group: "REGULATOR", code: "SFB", label: "(SFB) Securities and Futures Bureau", sortOrder: 34, meta: {"acronym": "SFB", "kind": "REGULATOR", "pdfPosition": 34} },
  { group: "REGULATOR", code: "FFAJ", label: "(FFAJ) The Financial Futures Association of Japan", sortOrder: 35, meta: {"acronym": "FFAJ", "kind": "REGULATOR", "pdfPosition": 35} },
  { group: "REGULATOR", code: "KNF", label: "(KNF) Polish Financial Supervision Authority", sortOrder: 36, meta: {"acronym": "KNF", "kind": "REGULATOR", "pdfPosition": 36} },
  { group: "REGULATOR", code: "BMA", label: "(BMA) The Bermuda Monetary Authority", sortOrder: 37, meta: {"acronym": "BMA", "kind": "REGULATOR", "pdfPosition": 37} },
  { group: "REGULATOR", code: "SCMN", label: "(SCMN) The Capital Market Commission", sortOrder: 38, meta: {"acronym": "SCMN", "kind": "REGULATOR", "pdfPosition": 38} },
  { group: "REGULATOR", code: "FSA_39", label: "(FSA) The Financial Supervision Authority", sortOrder: 39, meta: {"acronym": "FSA", "kind": "REGULATOR", "pdfPosition": 39} },
  { group: "REGULATOR", code: "CMVM", label: "(CMVM) Portuguese Securities Market Commission", sortOrder: 40, meta: {"acronym": "CMVM", "kind": "REGULATOR", "pdfPosition": 40} },
  { group: "REGULATOR", code: "FINRA", label: "(FINRA) The Financial Industry Regulatory Authority", sortOrder: 41, meta: {"acronym": "FINRA", "kind": "REGULATOR", "pdfPosition": 41, "pdfNote": "pdf line was 'The Financial Industry RegulatoryAuthorityFINRA' (acronym moved to front)"} },
  { group: "REGULATOR", code: "JFX", label: "(JFX) Jakarta Futures Exchange", sortOrder: 42, meta: {"acronym": "JFX", "kind": "EXCHANGE", "pdfPosition": 42, "pdfNote": "pdf had stray line 'CRCR' before it (artifact)"} },
  { group: "REGULATOR", code: "CBUAE", label: "(CBUAE) Central Bank of the U.A.E.", sortOrder: 43, meta: {"acronym": "CBUAE", "kind": "REGULATOR", "pdfPosition": 43} },
  { group: "REGULATOR", code: "TPEX", label: "(TPEx) Taipei Exchange", sortOrder: 44, meta: {"acronym": "TPEx", "kind": "EXCHANGE", "pdfPosition": 44} },
  { group: "REGULATOR", code: "FINCEN", label: "(FinCEN) Financial Crimes Enforcement Network", sortOrder: 45, meta: {"acronym": "FinCEN", "kind": "AML", "pdfPosition": 45} },
  { group: "REGULATOR", code: "IIROC", label: "(IIROC) Investment Industry Regulatory Organization of Canada", sortOrder: 46, meta: {"acronym": "IIROC", "kind": "REGULATOR", "pdfPosition": 46} },
  { group: "REGULATOR", code: "LFSA", label: "(LFSA) Labuan Financial Services Authority", sortOrder: 47, meta: {"acronym": "LFSA", "kind": "REGULATOR", "pdfPosition": 47} },
  { group: "REGULATOR", code: "CMA", label: "(CMA) Capital Markets Authority", sortOrder: 48, meta: {"acronym": "CMA", "kind": "REGULATOR", "pdfPosition": 48, "pdfNote": "pdf had trailing 'LEBANCN' (possibly Lebanon, unconfirmed)"} },
  { group: "REGULATOR", code: "LB", label: "(LB) Bank of Lithuania", sortOrder: 49, meta: {"acronym": "LB", "kind": "REGULATOR", "pdfPosition": 49} },
  { group: "REGULATOR", code: "SCA", label: "(SCA) Securities and Commodities Authority", sortOrder: 50, meta: {"acronym": "SCA", "kind": "REGULATOR", "pdfPosition": 50} },
  { group: "REGULATOR", code: "CDX", label: "(CDX) Indonesia Commodity and Derivatives Exchange", sortOrder: 51, meta: {"acronym": "CDX", "kind": "EXCHANGE", "pdfPosition": 51, "pdfNote": "pdf had trailing 'I' (artifact)"} },
  { group: "REGULATOR", code: "ADGM", label: "(ADGM) Abu Dhabi Global Market", sortOrder: 52, meta: {"acronym": "ADGM", "kind": "REGULATOR", "pdfPosition": 52} },
  { group: "REGULATOR", code: "CONSOB", label: "(CONSOB) National Commission for Companies and the Stock Exchange", sortOrder: 53, meta: {"acronym": "CONSOB", "kind": "REGULATOR", "pdfPosition": 53} },
  { group: "REGULATOR", code: "FSC_54", label: "(FSC) Financial Supervision Commission", sortOrder: 54, meta: {"acronym": "FSC", "kind": "REGULATOR", "pdfPosition": 54} },
  { group: "REGULATOR", code: "CNB", label: "(CNB) Czech national bank", sortOrder: 55, meta: {"acronym": "CNB", "kind": "REGULATOR", "pdfPosition": 55} },
  { group: "REGULATOR", code: "FSA_56", label: "(FSA) Financial Services Authority", sortOrder: 56, meta: {"acronym": "FSA", "kind": "REGULATOR", "pdfPosition": 56} },
  { group: "REGULATOR", code: "MTR", label: "(MTR) MajandusTegevuse Register", sortOrder: 57, meta: {"acronym": "MTR", "kind": "REGISTER", "pdfPosition": 57} },
  { group: "REGULATOR", code: "FSCSFB", label: "(FSCSFB) Financial Supervision Commission R.O.C. (Taiwan) / Securities and Futures Bureau", sortOrder: 58, meta: {"acronym": "FSCSFB", "kind": "REGULATOR", "pdfPosition": 58, "pdfNote": "pdf line merged two names; kept as ONE entry exactly as in the pdf"} },
  { group: "REGULATOR", code: "OTHER", label: "Other (specify)", sortOrder: 999, meta: {"allowsFreeText": true} },
  { group: "LANGUAGE", code: "AFRIKAANS", label: "Afrikaans", sortOrder: 1, meta: {} },
  { group: "LANGUAGE", code: "ALBANIAN", label: "Albanian", sortOrder: 2, meta: {} },
  { group: "LANGUAGE", code: "AMHARIC", label: "Amharic", sortOrder: 3, meta: {} },
  { group: "LANGUAGE", code: "ARABIC", label: "Arabic", sortOrder: 4, meta: {} },
  { group: "LANGUAGE", code: "ARMENIAN", label: "Armenian", sortOrder: 5, meta: {} },
  { group: "LANGUAGE", code: "ASSAMESE", label: "Assamese", sortOrder: 6, meta: {} },
  { group: "LANGUAGE", code: "AYMARA", label: "Aymara", sortOrder: 7, meta: {} },
  { group: "LANGUAGE", code: "AZERBAIJANI", label: "Azerbaijani", sortOrder: 8, meta: {} },
  { group: "LANGUAGE", code: "BAMBARA", label: "Bambara", sortOrder: 9, meta: {} },
  { group: "LANGUAGE", code: "BASQUE", label: "Basque", sortOrder: 10, meta: {} },
  { group: "LANGUAGE", code: "BELARUSIAN", label: "Belarusian", sortOrder: 11, meta: {} },
  { group: "LANGUAGE", code: "BENGALI", label: "Bengali", sortOrder: 12, meta: {} },
  { group: "LANGUAGE", code: "BHOJPURI", label: "Bhojpuri", sortOrder: 13, meta: {} },
  { group: "LANGUAGE", code: "BOSNIAN", label: "Bosnian", sortOrder: 14, meta: {} },
  { group: "LANGUAGE", code: "BULGARIAN", label: "Bulgarian", sortOrder: 15, meta: {} },
  { group: "LANGUAGE", code: "CATALAN", label: "Catalan", sortOrder: 16, meta: {} },
  { group: "LANGUAGE", code: "CEBUANO", label: "Cebuano", sortOrder: 17, meta: {} },
  { group: "LANGUAGE", code: "CHICHEWA", label: "Chichewa", sortOrder: 18, meta: {} },
  { group: "LANGUAGE", code: "CHINESE_SIMPLIFIED", label: "Chinese (Simplified)", sortOrder: 19, meta: {} },
  { group: "LANGUAGE", code: "CHINESE_TRADITIONAL", label: "Chinese (Traditional)", sortOrder: 20, meta: {} },
  { group: "LANGUAGE", code: "CORSICAN", label: "Corsican", sortOrder: 21, meta: {} },
  { group: "LANGUAGE", code: "CROATIAN", label: "Croatian", sortOrder: 22, meta: {} },
  { group: "LANGUAGE", code: "CZECH", label: "Czech", sortOrder: 23, meta: {} },
  { group: "LANGUAGE", code: "DANISH", label: "Danish", sortOrder: 24, meta: {} },
  { group: "LANGUAGE", code: "DHIVEHI", label: "Dhivehi", sortOrder: 25, meta: {} },
  { group: "LANGUAGE", code: "DOGRI", label: "Dogri", sortOrder: 26, meta: {} },
  { group: "LANGUAGE", code: "DUTCH", label: "Dutch", sortOrder: 27, meta: {} },
  { group: "LANGUAGE", code: "ENGLISH", label: "English", sortOrder: 28, meta: {} },
  { group: "LANGUAGE", code: "ESPERANTO", label: "Esperanto", sortOrder: 29, meta: {} },
  { group: "LANGUAGE", code: "ESTONIAN", label: "Estonian", sortOrder: 30, meta: {} },
  { group: "LANGUAGE", code: "EWE", label: "Ewe", sortOrder: 31, meta: {} },
  { group: "LANGUAGE", code: "FILIPINO", label: "Filipino", sortOrder: 32, meta: {} },
  { group: "LANGUAGE", code: "FINNISH", label: "Finnish", sortOrder: 33, meta: {} },
  { group: "LANGUAGE", code: "FRENCH", label: "French", sortOrder: 34, meta: {} },
  { group: "LANGUAGE", code: "FRISIAN", label: "Frisian", sortOrder: 35, meta: {} },
  { group: "LANGUAGE", code: "GALICIAN", label: "Galician", sortOrder: 36, meta: {} },
  { group: "LANGUAGE", code: "GEORGIAN", label: "Georgian", sortOrder: 37, meta: {} },
  { group: "LANGUAGE", code: "GERMAN", label: "German", sortOrder: 38, meta: {} },
  { group: "LANGUAGE", code: "GREEK", label: "Greek", sortOrder: 39, meta: {} },
  { group: "LANGUAGE", code: "GUARANI", label: "Guarani", sortOrder: 40, meta: {} },
  { group: "LANGUAGE", code: "GUJARATI", label: "Gujarati", sortOrder: 41, meta: {} },
  { group: "LANGUAGE", code: "HAITIAN_CREOLE", label: "Haitian Creole", sortOrder: 42, meta: {} },
  { group: "LANGUAGE", code: "HAUSA", label: "Hausa", sortOrder: 43, meta: {} },
  { group: "LANGUAGE", code: "HAWAIIAN", label: "Hawaiian", sortOrder: 44, meta: {} },
  { group: "LANGUAGE", code: "HEBREW", label: "Hebrew", sortOrder: 45, meta: {} },
  { group: "LANGUAGE", code: "HINDI", label: "Hindi", sortOrder: 46, meta: {} },
  { group: "LANGUAGE", code: "HMONG", label: "Hmong", sortOrder: 47, meta: {} },
  { group: "LANGUAGE", code: "HUNGARIAN", label: "Hungarian", sortOrder: 48, meta: {} },
  { group: "LANGUAGE", code: "ICELANDIC", label: "Icelandic", sortOrder: 49, meta: {} },
  { group: "LANGUAGE", code: "IGBO", label: "Igbo", sortOrder: 50, meta: {} },
  { group: "LANGUAGE", code: "ILOCANO", label: "Ilocano", sortOrder: 51, meta: {} },
  { group: "LANGUAGE", code: "INDONESIAN", label: "Indonesian", sortOrder: 52, meta: {} },
  { group: "LANGUAGE", code: "IRISH", label: "Irish", sortOrder: 53, meta: {} },
  { group: "LANGUAGE", code: "ITALIAN", label: "Italian", sortOrder: 54, meta: {} },
  { group: "LANGUAGE", code: "JAPANESE", label: "Japanese", sortOrder: 55, meta: {} },
  { group: "LANGUAGE", code: "JAVANESE", label: "Javanese", sortOrder: 56, meta: {} },
  { group: "LANGUAGE", code: "KANNADA", label: "Kannada", sortOrder: 57, meta: {} },
  { group: "LANGUAGE", code: "KAZAKH", label: "Kazakh", sortOrder: 58, meta: {} },
  { group: "LANGUAGE", code: "KHMER", label: "Khmer", sortOrder: 59, meta: {} },
  { group: "LANGUAGE", code: "KINYARWANDA", label: "Kinyarwanda", sortOrder: 60, meta: {} },
  { group: "LANGUAGE", code: "KONKANI", label: "Konkani", sortOrder: 61, meta: {} },
  { group: "LANGUAGE", code: "KOREAN", label: "Korean", sortOrder: 62, meta: {} },
  { group: "LANGUAGE", code: "KRIO", label: "Krio", sortOrder: 63, meta: {} },
  { group: "LANGUAGE", code: "KURDISH_KURMANJI", label: "Kurdish (Kurmanji)", sortOrder: 64, meta: {} },
  { group: "LANGUAGE", code: "KURDISH_SORANI", label: "Kurdish (Sorani)", sortOrder: 65, meta: {} },
  { group: "LANGUAGE", code: "KYRGYZ", label: "Kyrgyz", sortOrder: 66, meta: {} },
  { group: "LANGUAGE", code: "LAO", label: "Lao", sortOrder: 67, meta: {} },
  { group: "LANGUAGE", code: "LATIN", label: "Latin", sortOrder: 68, meta: {} },
  { group: "LANGUAGE", code: "LATVIAN", label: "Latvian", sortOrder: 69, meta: {} },
  { group: "LANGUAGE", code: "LINGALA", label: "Lingala", sortOrder: 70, meta: {} },
  { group: "LANGUAGE", code: "LITHUANIAN", label: "Lithuanian", sortOrder: 71, meta: {} },
  { group: "LANGUAGE", code: "LUGANDA", label: "Luganda", sortOrder: 72, meta: {} },
  { group: "LANGUAGE", code: "LUXEMBOURGISH", label: "Luxembourgish", sortOrder: 73, meta: {} },
  { group: "LANGUAGE", code: "MACEDONIAN", label: "Macedonian", sortOrder: 74, meta: {} },
  { group: "LANGUAGE", code: "MAITHILI", label: "Maithili", sortOrder: 75, meta: {} },
  { group: "LANGUAGE", code: "MALAGASY", label: "Malagasy", sortOrder: 76, meta: {} },
  { group: "LANGUAGE", code: "MALAY", label: "Malay", sortOrder: 77, meta: {} },
  { group: "LANGUAGE", code: "MALAYALAM", label: "Malayalam", sortOrder: 78, meta: {} },
  { group: "LANGUAGE", code: "MALTESE", label: "Maltese", sortOrder: 79, meta: {} },
  { group: "LANGUAGE", code: "MAORI", label: "Maori", sortOrder: 80, meta: {} },
  { group: "LANGUAGE", code: "MARATHI", label: "Marathi", sortOrder: 81, meta: {} },
  { group: "LANGUAGE", code: "MEITEILON_MANIPURI", label: "Meiteilon (Manipuri)", sortOrder: 82, meta: {} },
  { group: "LANGUAGE", code: "MIZO", label: "Mizo", sortOrder: 83, meta: {} },
  { group: "LANGUAGE", code: "MONGOLIAN", label: "Mongolian", sortOrder: 84, meta: {} },
  { group: "LANGUAGE", code: "MYANMAR_BURMESE", label: "Myanmar (Burmese)", sortOrder: 85, meta: {} },
  { group: "LANGUAGE", code: "NEPALI", label: "Nepali", sortOrder: 86, meta: {} },
  { group: "LANGUAGE", code: "NORWEGIAN", label: "Norwegian", sortOrder: 87, meta: {} },
  { group: "LANGUAGE", code: "ODIA_ORIYA", label: "Odia (Oriya)", sortOrder: 88, meta: {} },
  { group: "LANGUAGE", code: "OROMO", label: "Oromo", sortOrder: 89, meta: {} },
  { group: "LANGUAGE", code: "PASHTO", label: "Pashto", sortOrder: 90, meta: {} },
  { group: "LANGUAGE", code: "PERSIAN", label: "Persian", sortOrder: 91, meta: {} },
  { group: "LANGUAGE", code: "POLISH", label: "Polish", sortOrder: 92, meta: {} },
  { group: "LANGUAGE", code: "PORTUGUESE", label: "Portuguese", sortOrder: 93, meta: {} },
  { group: "LANGUAGE", code: "PUNJABI", label: "Punjabi", sortOrder: 94, meta: {} },
  { group: "LANGUAGE", code: "QUECHUA", label: "Quechua", sortOrder: 95, meta: {} },
  { group: "LANGUAGE", code: "ROMANIAN", label: "Romanian", sortOrder: 96, meta: {} },
  { group: "LANGUAGE", code: "RUSSIAN", label: "Russian", sortOrder: 97, meta: {} },
  { group: "LANGUAGE", code: "SAMOAN", label: "Samoan", sortOrder: 98, meta: {} },
  { group: "LANGUAGE", code: "SANSKRIT", label: "Sanskrit", sortOrder: 99, meta: {} },
  { group: "LANGUAGE", code: "SCOTS_GAELIC", label: "Scots Gaelic", sortOrder: 100, meta: {} },
  { group: "LANGUAGE", code: "SEPEDI", label: "Sepedi", sortOrder: 101, meta: {} },
  { group: "LANGUAGE", code: "SERBIAN", label: "Serbian", sortOrder: 102, meta: {} },
  { group: "LANGUAGE", code: "SESOTHO", label: "Sesotho", sortOrder: 103, meta: {} },
  { group: "LANGUAGE", code: "SHONA", label: "Shona", sortOrder: 104, meta: {} },
  { group: "LANGUAGE", code: "SINDHI", label: "Sindhi", sortOrder: 105, meta: {} },
  { group: "LANGUAGE", code: "SINHALA", label: "Sinhala", sortOrder: 106, meta: {} },
  { group: "LANGUAGE", code: "SLOVAK", label: "Slovak", sortOrder: 107, meta: {} },
  { group: "LANGUAGE", code: "SLOVENIAN", label: "Slovenian", sortOrder: 108, meta: {} },
  { group: "LANGUAGE", code: "SOMALI", label: "Somali", sortOrder: 109, meta: {} },
  { group: "LANGUAGE", code: "SPANISH", label: "Spanish", sortOrder: 110, meta: {} },
  { group: "LANGUAGE", code: "SUNDANESE", label: "Sundanese", sortOrder: 111, meta: {} },
  { group: "LANGUAGE", code: "SWAHILI", label: "Swahili", sortOrder: 112, meta: {} },
  { group: "LANGUAGE", code: "SWEDISH", label: "Swedish", sortOrder: 113, meta: {} },
  { group: "LANGUAGE", code: "TAJIK", label: "Tajik", sortOrder: 114, meta: {} },
  { group: "LANGUAGE", code: "TAMIL", label: "Tamil", sortOrder: 115, meta: {} },
  { group: "LANGUAGE", code: "TATAR", label: "Tatar", sortOrder: 116, meta: {} },
  { group: "LANGUAGE", code: "TELUGU", label: "Telugu", sortOrder: 117, meta: {} },
  { group: "LANGUAGE", code: "THAI", label: "Thai", sortOrder: 118, meta: {} },
  { group: "LANGUAGE", code: "TIGRINYA", label: "Tigrinya", sortOrder: 119, meta: {} },
  { group: "LANGUAGE", code: "TSONGA", label: "Tsonga", sortOrder: 120, meta: {} },
  { group: "LANGUAGE", code: "TURKISH", label: "Turkish", sortOrder: 121, meta: {} },
  { group: "LANGUAGE", code: "TURKMEN", label: "Turkmen", sortOrder: 122, meta: {} },
  { group: "LANGUAGE", code: "TWI", label: "Twi", sortOrder: 123, meta: {} },
  { group: "LANGUAGE", code: "UKRAINIAN", label: "Ukrainian", sortOrder: 124, meta: {} },
  { group: "LANGUAGE", code: "URDU", label: "Urdu", sortOrder: 125, meta: {} },
  { group: "LANGUAGE", code: "UYGHUR", label: "Uyghur", sortOrder: 126, meta: {} },
  { group: "LANGUAGE", code: "UZBEK", label: "Uzbek", sortOrder: 127, meta: {} },
  { group: "LANGUAGE", code: "VIETNAMESE", label: "Vietnamese", sortOrder: 128, meta: {} },
  { group: "LANGUAGE", code: "WELSH", label: "Welsh", sortOrder: 129, meta: {} },
  { group: "LANGUAGE", code: "XHOSA", label: "Xhosa", sortOrder: 130, meta: {} },
  { group: "LANGUAGE", code: "YIDDISH", label: "Yiddish", sortOrder: 131, meta: {} },
  { group: "LANGUAGE", code: "YORUBA", label: "Yoruba", sortOrder: 132, meta: {} },
  { group: "LANGUAGE", code: "ZULU", label: "Zulu", sortOrder: 133, meta: {} },
  { group: "CURRENCY", code: "USD", label: "USD (United States of America)", sortOrder: 1, meta: {"isCent": false} },
  { group: "CURRENCY", code: "USC", label: "USC (United States Cent)", sortOrder: 2, meta: {"isCent": true} },
  { group: "CURRENCY", code: "GBP", label: "GBP (United Kingdom)", sortOrder: 3, meta: {"isCent": false} },
  { group: "CURRENCY", code: "EUR", label: "EUR", sortOrder: 4, meta: {"isCent": false} },
  { group: "CURRENCY", code: "AUD", label: "AUD", sortOrder: 5, meta: {"isCent": false} },
  { group: "CURRENCY", code: "JPY", label: "JPY", sortOrder: 6, meta: {"isCent": false} },
  { group: "CURRENCY", code: "AED", label: "AED", sortOrder: 7, meta: {"isCent": false} },
  { group: "CURRENCY", code: "ZAR", label: "ZAR", sortOrder: 8, meta: {"isCent": false} },
  { group: "CURRENCY", code: "CHF", label: "CHF", sortOrder: 9, meta: {"isCent": false} },
  { group: "CURRENCY", code: "OTHER", label: "Other (specify)", sortOrder: 999, meta: {"allowsFreeText": true} },
  { group: "LICENSE_STATUS", code: "REGULATED", label: "Regulated", sortOrder: 1, meta: {} },
  { group: "LICENSE_STATUS", code: "UNREGULATED", label: "Unregulated", sortOrder: 2, meta: {} },
  { group: "LICENSE_STATUS", code: "REVOKED", label: "Revoked", sortOrder: 3, meta: {} },
  { group: "LICENSE_STATUS", code: "AUTHORIZED", label: "Authorized", sortOrder: 4, meta: {} },
  { group: "LICENSE_STATUS", code: "UNAUTHORIZED", label: "Unauthorized", sortOrder: 5, meta: {} },
  { group: "LICENSE_STATUS", code: "GENERAL_REGISTRATION", label: "General registration", sortOrder: 6, meta: {} },
  { group: "LICENSE_STATUS", code: "EXCEEDED", label: "Exceeded", sortOrder: 7, meta: {} },
  { group: "LICENSE_STATUS", code: "EXPIRED", label: "Expired", sortOrder: 8, meta: {} },
  { group: "DEPOSIT_BONUS", code: "0", label: "0%", sortOrder: 1, meta: {"percent": 0} },
  { group: "DEPOSIT_BONUS", code: "5", label: "5%", sortOrder: 2, meta: {"percent": 5} },
  { group: "DEPOSIT_BONUS", code: "10", label: "10%", sortOrder: 3, meta: {"percent": 10} },
  { group: "DEPOSIT_BONUS", code: "15", label: "15%", sortOrder: 4, meta: {"percent": 15} },
  { group: "DEPOSIT_BONUS", code: "20", label: "20%", sortOrder: 5, meta: {"percent": 20} },
  { group: "DEPOSIT_BONUS", code: "25", label: "25%", sortOrder: 6, meta: {"percent": 25} },
  { group: "DEPOSIT_BONUS", code: "30", label: "30%", sortOrder: 7, meta: {"percent": 30} },
  { group: "DEPOSIT_BONUS", code: "35", label: "35%", sortOrder: 8, meta: {"percent": 35} },
  { group: "DEPOSIT_BONUS", code: "40", label: "40%", sortOrder: 9, meta: {"percent": 40} },
  { group: "DEPOSIT_BONUS", code: "45", label: "45%", sortOrder: 10, meta: {"percent": 45} },
  { group: "DEPOSIT_BONUS", code: "50", label: "50%", sortOrder: 11, meta: {"percent": 50} },
  { group: "DEPOSIT_BONUS", code: "55", label: "55%", sortOrder: 12, meta: {"percent": 55} },
  { group: "DEPOSIT_BONUS", code: "60", label: "60%", sortOrder: 13, meta: {"percent": 60} },
  { group: "DEPOSIT_BONUS", code: "65", label: "65%", sortOrder: 14, meta: {"percent": 65} },
  { group: "DEPOSIT_BONUS", code: "70", label: "70%", sortOrder: 15, meta: {"percent": 70} },
  { group: "DEPOSIT_BONUS", code: "75", label: "75%", sortOrder: 16, meta: {"percent": 75} },
  { group: "DEPOSIT_BONUS", code: "80", label: "80%", sortOrder: 17, meta: {"percent": 80} },
  { group: "DEPOSIT_BONUS", code: "85", label: "85%", sortOrder: 18, meta: {"percent": 85} },
  { group: "DEPOSIT_BONUS", code: "90", label: "90%", sortOrder: 19, meta: {"percent": 90} },
  { group: "DEPOSIT_BONUS", code: "95", label: "95%", sortOrder: 20, meta: {"percent": 95} },
  { group: "DEPOSIT_BONUS", code: "100", label: "100%", sortOrder: 21, meta: {"percent": 100} },
  { group: "LEVERAGE", code: "1:1", label: "1:1", sortOrder: 1, meta: {"ratio": 1} },
  { group: "LEVERAGE", code: "1:5", label: "1:5", sortOrder: 2, meta: {"ratio": 5} },
  { group: "LEVERAGE", code: "1:25", label: "1:25", sortOrder: 3, meta: {"ratio": 25} },
  { group: "LEVERAGE", code: "1:50", label: "1:50", sortOrder: 4, meta: {"ratio": 50} },
  { group: "LEVERAGE", code: "1:80", label: "1:80", sortOrder: 5, meta: {"ratio": 80} },
  { group: "LEVERAGE", code: "1:100", label: "1:100", sortOrder: 6, meta: {"ratio": 100} },
  { group: "LEVERAGE", code: "1:125", label: "1:125", sortOrder: 7, meta: {"ratio": 125} },
  { group: "LEVERAGE", code: "1:150", label: "1:150", sortOrder: 8, meta: {"ratio": 150} },
  { group: "LEVERAGE", code: "1:200", label: "1:200", sortOrder: 9, meta: {"ratio": 200} },
  { group: "LEVERAGE", code: "1:250", label: "1:250", sortOrder: 10, meta: {"ratio": 250} },
  { group: "LEVERAGE", code: "1:300", label: "1:300", sortOrder: 11, meta: {"ratio": 300} },
  { group: "LEVERAGE", code: "1:350", label: "1:350", sortOrder: 12, meta: {"ratio": 350} },
  { group: "LEVERAGE", code: "1:400", label: "1:400", sortOrder: 13, meta: {"ratio": 400} },
  { group: "LEVERAGE", code: "1:450", label: "1:450", sortOrder: 14, meta: {"ratio": 450} },
  { group: "LEVERAGE", code: "1:500", label: "1:500", sortOrder: 15, meta: {"ratio": 500} },
  { group: "LEVERAGE", code: "1:1000", label: "1:1000", sortOrder: 16, meta: {"ratio": 1000} },
  { group: "LEVERAGE", code: "1:1500", label: "1:1500", sortOrder: 17, meta: {"ratio": 1500} },
  { group: "LEVERAGE", code: "1:2000", label: "1:2000", sortOrder: 18, meta: {"ratio": 2000} },
  { group: "LEVERAGE", code: "1:2500", label: "1:2500", sortOrder: 19, meta: {"ratio": 2500} },
  { group: "LEVERAGE", code: "1:3000", label: "1:3000", sortOrder: 20, meta: {"ratio": 3000} },
  { group: "LEVERAGE", code: "1:4000", label: "1:4000", sortOrder: 21, meta: {"ratio": 4000} },
  { group: "LEVERAGE", code: "1:5000", label: "1:5000", sortOrder: 22, meta: {"ratio": 5000} },
  { group: "LEVERAGE", code: "1:10000", label: "1:10000", sortOrder: 23, meta: {"ratio": 10000} },
  { group: "TIMEFRAME", code: "M1", label: "M1", sortOrder: 1, meta: {} },
  { group: "TIMEFRAME", code: "M5", label: "M5", sortOrder: 2, meta: {} },
  { group: "TIMEFRAME", code: "M15", label: "M15", sortOrder: 3, meta: {} },
  { group: "TIMEFRAME", code: "M30", label: "M30", sortOrder: 4, meta: {} },
  { group: "TIMEFRAME", code: "H1", label: "H1", sortOrder: 5, meta: {} },
  { group: "TIMEFRAME", code: "H4", label: "H4", sortOrder: 6, meta: {} },
  { group: "TIMEFRAME", code: "D1", label: "D1", sortOrder: 7, meta: {} },
  { group: "TIMEFRAME", code: "W1", label: "W1", sortOrder: 8, meta: {} },
  { group: "TIMEFRAME", code: "MN", label: "MN", sortOrder: 9, meta: {} },
];
